// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htmhbqswuatbuorksosu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bWhicXN3dWF0YnVvcmtzb3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDU1NDMsImV4cCI6MjA2MzQyMTU0M30.yr6Apcb3HyAIh4XOMiZl0HAvjUnCinubrW85bEohtYM"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);